name: Continuous Integration with GitHub Actions

on:
  push:
    branches: 
      - "master" 
  pull_request:
    branches: 
      - "master" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Download wait-for-it.sh
      run: |
        curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        chmod +x wait-for-it.sh

    - name: Build Application JAR
      working-directory: .
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: .
      run: docker compose build

    - name: Start MySQL with Docker Compose and wait for it
      working-directory: .
      run: |
        docker compose up -d db
        ./wait-for-it.sh db:3308 --timeout=60 --strict -- echo "MySQL is up"

    - name: Start Application with Docker Compose
      working-directory: .
      run: docker compose up -d cashflowkeeper

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/cashflowkeeper:latest ${{ secrets.DOCKER_USERNAME }}/cashflowkeeper:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/cashflowkeeper:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/cashflowkeeper:latest
